[package]
name = "a1-fuel-tyrrany"
version = "0.1.0"
authors = ["Nikita Barsukov <nbarsukov@ptsecurity.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
